# Generated by Django 2.2.4 on 2020-04-21 13:07

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('customer', models.UUIDField(blank=True, null=True)),
                ('itemsInOrder', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('billing', models.UUIDField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
