# Generated by Django 2.2.4 on 2020-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
